import os

APP_NAME = 'niponcred-api'
APP_VERSION = '1.0.0'
API_VERSION = 'v1'
APP_WEB_URL = os.environ['APP_WEB_URL']

DATABASE_URL = os.environ['DATABASE_URL']

SENDGRID_API_KEY = os.environ['SENDGRID_API_KEY']

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 5
SQLALCHEMY_MAX_OVERFLOW = 10
SQLALCHEMY_POOL_RECYCLE = 60 * 5
SQLALCHEMY_POOL_TIMEOUT = 10
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_ECHO = False